### PR TITLE
ENH: Add VTK point interpolator resampling

### PR DESCRIPTION
**Pull request by thewtex**
These require VTK7.

CC: @wschroed

### CODE REVIEW

**Comment by jcfr** [comment]
Hi Matt,

Latest Vtk7 has been integrated into Slicer and OpenGL2 has been re enabled
yesterday.

Hth
Jc

**Comment by thewtex** [comment]
@jcfr This is excellent! My local tests with the Slicer Docker images built well. I guessing that Travis will confirm :-)

**Comment by jcfr** [comment]
And this morning, I also triggered the rebuild of the docker images. They
should be up to date (with build time metadata too)

Jc

PS: boarding on my flight to SFO :)

**Comment by thewtex** [comment]
:8ball: Niiiice! Enjoy California!

**Pull request merged**
