### PR TITLE
Make module dependencies on ITK and VTK explicit

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by jcfr** [comment]
Could you confirm that the latest changes were integrated to support bundling the extension in a custom application ?

**Comment by dzenanz** [comment]
Yes.

**Comment by jcfr** [comment]
> re: yes

Thanks for confirming. We will have to conditionally list `ITK` and `VTK`, I will do a follow-up a pull request

**Comment by dzenanz** [comment]
Is a follow-up PR required?

**Pull request merged**
